# Generated by Django 2.2.4 on 2019-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
