# Generated by Django 2.2.4 on 2019-08-20 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0003_auto_20190820_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='category',
        ),
        migrations.AddField(
            model_name='favorite',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favorite', to='favorite_things.Category'),
        ),
    ]
