# Generated by Django 2.2.4 on 2019-08-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0004_auto_20190820_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelChangeLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(blank=True, db_index=True)),
                ('data', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'model_change_logs',
            },
        ),
    ]
