# Generated by Django 2.2.4 on 2019-08-20 22:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite_things', '0007_auto_20190820_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelchangelogsmodel',
            old_name='favorite_id',
            new_name='favorite',
        ),
        migrations.AlterField(
            model_name='modelchangelogsmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
